name: Build Index

on:
  push:
    paths:
      - 'docs/**'
      - 'meta/*.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node build-index.js
      - name: Commit updated index
        run: |
          if [ -n "$(git status --porcelain index.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.json
            git commit -m "chore: update index"
            git push
          fi
